robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_follow_r
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT3M9NVB-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [4.71239, 3.14159, 3.14159, 3.14159, 3.14159, 6.28319]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [7, 142.12109375, 201.62109375]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
hz: 30
max_steps: 1000
mxid: 19443010E163142F00